### ISSUE TITLE
calman wont load .edr generated by ccss2edr

### ISSUE THREAD

**Issue by 24fpsDaVinci** [ypomortsev/ccss2edr#2]
i generated an edr using ccss supplied by displaycal
when i try to load it using calman home I get this error

![Capture](https://user-images.githubusercontent.com/3499141/146820189-1694a4b9-9774-44bc-99c1-e892b61b6af0.PNG)

i've attached the generated .edr file here
[LG-Oled-6-Series-Generated.zip](https://github.com/ypomortsev/ccss2edr/files/7749361/LG-Oled-6-Series-Generated.zip)

**Comment by ypomortsev** [comment]
Thanks for the issue report.

Please try the following EDR, converted from [LG OLED 6-Series (i1 Pro 2, ColorMunki Photo).ccss](https://colorimetercorrections.displaycal.net/hash/2e7d6f552bb8b62118c172a49f1ade30/LG%20OLED%206-Series%20%28i1%20Pro%202%2C%20ColorMunki%20Photo%29.ccss)

[LG-Oled-6-Series_fixed.zip](https://github.com/ypomortsev/ccss2edr/files/8526171/LG-Oled-6-Series_fixed.zip)

**Comment by 24fpsDaVinci** [comment]
> Please try the following EDR, converted from [LG OLED 6-Series (i1 Pro 2, ColorMunki Photo).ccss](https://colorimetercorrections.displaycal.net/hash/2e7d6f552bb8b62118c172a49f1ade30/LG%20OLED%206-Series%20%28i1%20Pro%202%2C%20ColorMunki%20Photo%29.ccss)

thank you very much, what was the issue here?

**Comment by ypomortsev** [comment]
The i1Display Pro SDK requires that the spectral data in the EDR file starts at 380 nm, but this particular CCSS starts at 370 nm (see SPECTRAL_START_NM).

ccss2edr now removes the extra spectral bands below 380 nm during conversion.
